### PR TITLE
fix: don't execute operations when offline

### PR DESCRIPTION
**Pull request by carlosdp**
This change prevents executing operations that are passed to the link if the socket is in the offline state. Without this change, there is a race condition where if the socket is killed and restarted while subscription operations are still being sent to the link from something like Apollo, the operations are duplicated once reconnected, causing duplicate subscriptions.

This happens because the `execute` on each operation will survive the reconnection if it is fast enough, so that original `execute` will complete, and then we re-execute it from the `operations` list in `onConnect`.

### CODE REVIEW

**Review by GailWilson — COMMENTED** [review]
👍

**Comment by n1ru4l** [comment]
@carlosdp Hey, thank you for this contribution! Some more things to consider:

1. Can you please generate a changeset and commit it using `yarn changeset`?
2. Should the query re-execution (after going online) be done with the same operation id, instead of using a new one?
3. Should this library be responsible for doing the re-execution after going online again vs. providing primitives to implement this behavior in user-land?

**Comment by n1ru4l** [comment]
hey @carlosdp any updates?

**Comment by carlosdp** [comment]
1. Added the changeset
2. It should use the same operation ID, it's a brand new socket connection
3. I believe it should be done by the library, that's what I would expect as a user. The developer doesn't really have great insight into the internal state of the subscription layer, it would be unnecessarily difficult to reason about when to trigger re-subscriptions. Whereas, this library has all the information needed, it just wasn't accounting for the behavior of the socket-io library when a socket connection is interrupted. Also, it would be a breaking change to have it not handle re-execution 😃

**Pull request merged**
